let log = (x718) => console.log(x718)
let x = [
[ "'CUT01'", 'Interior.SetVisible(4)', "Cutscene.Load('PROLOG1')" ],
[ "'CUT02'", 'Interior.SetVisible(3)', "Cutscene.Load('INTRO1A')" ],
[ "'CUT03'", 'Interior.SetVisible(0)', "Cutscene.Load('INTRO1B')" ],
[ "'CUT04'", 'Interior.SetVisible(2)', "Cutscene.Load('INTRO2A')" ],
[ "'CUT05'", 'Interior.SetVisible(0)', "Cutscene.Load('SWEET1A')" ],
[ "'CUT06'", 'Interior.SetVisible(1)', "Cutscene.Load('SWEET1B')" ],
[ "'CUT07'", 'Interior.SetVisible(1)', "Cutscene.Load('SWEET3A')" ],
[ "'CUT08'", 'Interior.SetVisible(0)', "Cutscene.Load('SWEET3B')" ],
[ "'CUT09'", 'Interior.SetVisible(0)', "Cutscene.Load('SWEET2A')" ],
[ "'CUT10'", 'Interior.SetVisible(0)', "Cutscene.Load('SWEET2B')" ],
[ "'CUT11'", 'Interior.SetVisible(0)', "Cutscene.Load('SWEET4A')" ],
[ "'CUT12'", 'Interior.SetVisible(1)', "Cutscene.Load('SWEET5A')" ],
[ "'CUT13'", 'Interior.SetVisible(1)', "Cutscene.Load('SWEET6A')" ],
[ "'CUT14'", 'Interior.SetVisible(0)', "Cutscene.Load('SWEET6B')" ],
[ "'CUT15'", 'Interior.SetVisible(0)', "Cutscene.Load('SWEET7A')" ],
[ "'CUT16'", 'Interior.SetVisible(0)', "Cutscene.Load('SMOKE1A')" ],
[ "'CUT17'", 'Interior.SetVisible(0)', "Cutscene.Load('SMOKE1B')" ],
[ "'CUT18'", 'Interior.SetVisible(0)', "Cutscene.Load('SMOKE2A')" ],
[ "'CUT19'", 'Interior.SetVisible(0)', "Cutscene.Load('SMOKE2B')" ],
[ "'CUT20'", 'Interior.SetVisible(0)', "Cutscene.Load('SMOKE3A')" ],
[ "'CUT21'", 'Interior.SetVisible(0)', "Cutscene.Load('SMOKE4A')" ],
[ "'CUT22'", 'Interior.SetVisible(0)', "Cutscene.Load('RYDER1A')" ],
[ "'CUT23'", 'Interior.SetVisible(0)', "Cutscene.Load('RYDER2A')" ],
[ "'CUT24'", 'Interior.SetVisible(2)', "Cutscene.Load('RYDER3A')" ],
[ "'CUT25'", 'Interior.SetVisible(0)', "Cutscene.Load('STRAP1A')" ],
[ "'CUT26'", 'Interior.SetVisible(0)', "Cutscene.Load('STRAP2A')" ],
[ "'CUT27'", 'Interior.SetVisible(0)', "Cutscene.Load('STRAP3A')" ],
[ "'CUT28'", 'Interior.SetVisible(0)', "Cutscene.Load('STRAP4A')" ],
[ "'CUT29'", 'Interior.SetVisible(3)', "Cutscene.Load('Strp4b1')" ],
[ "'CUT135'", 'Interior.SetVisible(0)', "Cutscene.Load('Strp4b2')" ],
[ "'CUT30'", 'Interior.SetVisible(7)', "Cutscene.Load('CRASH1A')" ],
[ "'CUT31'", 'Interior.SetVisible(0)', "Cutscene.Load('CRASH2A')" ],
[ "'CUT32'", 'Interior.SetVisible(0)', "Cutscene.Load('CRASH3A')" ],
[ "'CUT33'", 'Interior.SetVisible(0)', "Cutscene.Load('CESAR1A')" ],
[ "'CUT34'", 'Interior.SetVisible(0)', "Cutscene.Load('CESAR2A')" ],
[ "'CUT35'", 'Interior.SetVisible(1)', "Cutscene.Load('FINAL1A')" ],
[ "'CUT36'", 'Interior.SetVisible(1)', "Cutscene.Load('FINAL2A')" ],
[ "'CUT37'", 'Interior.SetVisible(0)', "Cutscene.Load('FINAL2B')" ],
[ "'CUT38'", 'Interior.SetVisible(0)', "Cutscene.Load('BCRAS1')" ],
[ "'CUT39'", 'Interior.SetVisible(2)', "Cutscene.Load('BCESAR2')" ],
[ "'CUT40'", 'Interior.SetVisible(0)', "Cutscene.Load('BCESAR4')" ],
[ "'CUT41'", 'Interior.SetVisible(0)', "Cutscene.Load('BCESA4W')" ],
[ "'CUT42'", 'Interior.SetVisible(0)', "Cutscene.Load('BCESA5W')" ],
[ "'CUT43'", 'Interior.SetVisible(1)', "Cutscene.Load('CAT_1')" ],
[ "'CUT44'", 'Interior.SetVisible(0)', "Cutscene.Load('CAT_2')" ],
[ "'CUT45'", 'Interior.SetVisible(0)', "Cutscene.Load('CAT_3')" ],
[ "'CUT46'", 'Interior.SetVisible(0)', "Cutscene.Load('CAT_4')" ],
[ "'CUT47'", 'Interior.SetVisible(0)', "Cutscene.Load('DESERT1')" ],
[ "'CUT48'", 'Interior.SetVisible(0)', "Cutscene.Load('DESERT2')" ],
[ "'CUT49'", 'Interior.SetVisible(0)', "Cutscene.Load('DESERT3')" ],
[ "'CUT50'", 'Interior.SetVisible(0)', "Cutscene.Load('DESERT4')" ],
[ "'CUT52'", 'Interior.SetVisible(0)', "Cutscene.Load('DESERT6')" ],
[ "'CUT54'", 'Interior.SetVisible(0)', "Cutscene.Load('DESERT8')" ],
[ "'CUT55'", 'Interior.SetVisible(0)', "Cutscene.Load('DESERT9')" ],
[ "'CUT56'", 'Interior.SetVisible(0)', "Cutscene.Load('DES_10A')" ],
[ "'CUT57'", 'Interior.SetVisible(0)', "Cutscene.Load('DES_10B')" ],
[ "'CUT60'", 'Interior.SetVisible(3)', "Cutscene.Load('FARL_2A')" ],
[ "'CUT61'", 'Interior.SetVisible(3)', "Cutscene.Load('FARL_3A')" ],
[ "'CUT62'", 'Interior.SetVisible(0)', "Cutscene.Load('FARL_3B')" ],
[ "'CUT63'", 'Interior.SetVisible(1)', "Cutscene.Load('FARL_4A')" ],
[ "'CUT64'", 'Interior.SetVisible(1)', "Cutscene.Load('FARL_5A')" ],
[ "'CUT65'", 'Interior.SetVisible(1)', "Cutscene.Load('GARAG1B')" ],
[ "'CUT66'", 'Interior.SetVisible(1)', "Cutscene.Load('GARAG1C')" ],
[ "'CUT67'", 'Interior.SetVisible(1)', "Cutscene.Load('GARAG3A')" ],
[ "'CUT69'", 'Interior.SetVisible(1)', "Cutscene.Load('SCRASH1')" ],
[ "'CUT70'", 'Interior.SetVisible(1)', "Cutscene.Load('SCRASH2')" ],
[ "'CUT71'", 'Interior.SetVisible(1)', "Cutscene.Load('STEAL_1')" ],
[ "'CUT72'", 'Interior.SetVisible(1)', "Cutscene.Load('STEAL_2')" ],
[ "'CUT74'", 'Interior.SetVisible(1)', "Cutscene.Load('STEAL_4')" ],
[ "'CUT75'", 'Interior.SetVisible(1)', "Cutscene.Load('STEAL_5')" ],
[ "'CUT76'", 'Interior.SetVisible(1)', "Cutscene.Load('SYND_2A')" ],
[ "'CUT77'", 'Interior.SetVisible(3)', "Cutscene.Load('SYND_2B')" ],
[ "'CUT78'", 'Interior.SetVisible(0)', "Cutscene.Load('SYND_3A')" ],
[ "'CUT79'", 'Interior.SetVisible(1)', "Cutscene.Load('SYND_4A')" ],
[ "'CUT80'", 'Interior.SetVisible(1)', "Cutscene.Load('SYND_7')" ],
[ "'CUT81'", 'Interior.SetVisible(2)', "Cutscene.Load('TRUTH_1')" ],
[ "'CUT82'", 'Interior.SetVisible(0)', "Cutscene.Load('TRUTH_2')" ],
[ "'CUT83'", 'Interior.SetVisible(1)', "Cutscene.Load('WOOZI1A')" ],
[ "'CUT84'", 'Interior.SetVisible(1)', "Cutscene.Load('WOOZIE2')" ],
[ "'CUT86'", 'Interior.SetVisible(1)', "Cutscene.Load('WOOZIE4')" ],
[ "'CUT87'", 'Interior.SetVisible(6)', "Cutscene.Load('ZERO_1')" ],
[ "'CUT88'", 'Interior.SetVisible(6)', "Cutscene.Load('ZERO_2')" ],
[ "'CUT89'", 'Interior.SetVisible(6)', "Cutscene.Load('ZERO_3')" ],
[ "'CUT90'", 'Interior.SetVisible(6)', "Cutscene.Load('ZERO_4')" ],
[ "'CUT92'", 'Interior.SetVisible(0)', "Cutscene.Load('BCESAR5')" ],
[ "'CUT94'", 'Interior.SetVisible(0)', "Cutscene.Load('D8_ALT')" ],
[ "'CUT95'", 'Interior.SetVisible(0)', "Cutscene.Load('D10_ALT')" ],
[ "'CUT96'", 'Interior.SetVisible(0)', "Cutscene.Load('SYND_3B')" ],
[ "'CUT97'", 'Interior.SetVisible(3)', "Cutscene.Load('SYND_4B')" ],
[ "'CUT98'", 'Interior.SetVisible(1)', "Cutscene.Load('CAS_1a')" ],
[ "'CUT83'", 'Interior.SetVisible(1)', "Cutscene.Load('WOOZI1B')" ],
[ "'CUT100'", 'Interior.SetVisible(1)', "Cutscene.Load('CAS_2')" ],
[ "'CUT101'", 'Interior.SetVisible(1)', "Cutscene.Load('CAS_3')" ],
[ "'CUT102'", 'Interior.SetVisible(0)', "Cutscene.Load('CAS_4a')" ],
[ "'CUT103'", 'Interior.SetVisible(0)', "Cutscene.Load('CAS_4b')" ],
[ "'CUT104'", 'Interior.SetVisible(2)', "Cutscene.Load('CAS_4c')" ],
[ "'CUT105'", 'Interior.SetVisible(2)', "Cutscene.Load('CAS_5a')" ],
[ "'CUT106'", 'Interior.SetVisible(2)', "Cutscene.Load('CAS_6a')" ],
[ "'CUT107'", 'Interior.SetVisible(1)', "Cutscene.Load('CAS6b_1')" ],
[ "'CUT109'", 'Interior.SetVisible(1)', "Cutscene.Load('CAS_7b')" ],
[ "'CUT110'", 'Interior.SetVisible(2)', "Cutscene.Load('Cas_9a1')" ],
[ "'CUT111'", 'Interior.SetVisible(2)', "Cutscene.Load('CAS_11a')" ],
[ "'CUT112'", 'Interior.SetVisible(0)', "Cutscene.Load('HEIST1a')" ],
[ "'CUT113'", 'Interior.SetVisible(0)', "Cutscene.Load('HEIST2a')" ],
[ "'CUT115'", 'Interior.SetVisible(0)', "Cutscene.Load('HEIST4a')" ],
[ "'CUT116'", 'Interior.SetVisible(0)', "Cutscene.Load('HEIST5a')" ],
[ "'CUT117'", 'Interior.SetVisible(0)', "Cutscene.Load('HEIST6a')" ],
[ "'CUT118'", 'Interior.SetVisible(0)', "Cutscene.Load('HEIST8a')" ],
[ "'CUT119'", 'Interior.SetVisible(0)', "Cutscene.Load('CRASHV1')" ],
[ "'CUT120'", 'Interior.SetVisible(0)', "Cutscene.Load('CRASV2A')" ],
[ "'CUT121'", 'Interior.SetVisible(0)', "Cutscene.Load('DOC_2')" ],
[ "'CUT122'", 'Interior.SetVisible(1)', "Cutscene.Load('BHILL1')" ],
[ "'CUT123'", 'Interior.SetVisible(5)', "Cutscene.Load('BHILL2')" ],
[ "'CUT124'", 'Interior.SetVisible(5)', "Cutscene.Load('BHILL3a')" ],
[ "'CUT125'", 'Interior.SetVisible(0)', "Cutscene.Load('BHILL3b')" ],
[ "'CUT126'", 'Interior.SetVisible(0)', "Cutscene.Load('BHILL3c')" ],
[ "'CUT127'", 'Interior.SetVisible(5)', "Cutscene.Load('BHILL5a')" ],
[ "'CUT128'", 'Interior.SetVisible(3)', "Cutscene.Load('BHILL5b')" ],
[ "'CUT129'", 'Interior.SetVisible(3)', "Cutscene.Load('GROVE1a')" ],
[ "'CUT130'", 'Interior.SetVisible(3)', "Cutscene.Load('GROVE1b')" ],
[ "'CUT131'", 'Interior.SetVisible(2)', "Cutscene.Load('GROVE1c')" ],
[ "'CUT132'", 'Interior.SetVisible(1)', "Cutscene.Load('GROVE2')" ],
[ "'CUT133'", 'Interior.SetVisible(5)', "Cutscene.Load('RIOT_1A')" ],
[ "'CUT134'", 'Interior.SetVisible(1)', "Cutscene.Load('RIOT_2')" ],
[ "'CUT137'", 'Interior.SetVisible(1)', "Cutscene.Load('RIOT_4a')" ],
[ "'CUT138'", 'Interior.SetVisible(0)', "Cutscene.Load('RIOT_4b')" ],
[ "'CUT139'", 'Interior.SetVisible(2)', "Cutscene.Load('RIOT_4c')" ],
[ "'CUT140'", 'Interior.SetVisible(2)', "Cutscene.Load('RIOT_4d')" ],
[ "'CUT141'", 'Interior.SetVisible(0)', "Cutscene.Load('Riot4e1')" ],
[ "'CUT142'", 'Interior.SetVisible(3)', "Cutscene.Load('EPILOG')" ],
[ "'CUT143'", 'Interior.SetVisible(3)', "Cutscene.Load('SWEET1C')" ],
[ "'CUT150'", 'Interior.SetVisible(0)', "Cutscene.Load('PROLOG2')" ],
[ "'CUT151'", 'Interior.SetVisible(0)', "Cutscene.Load('PROLOG3')" ],
[ "'CUT152'", 'Interior.SetVisible(0)', "Cutscene.Load('BCRAS2')" ],
[ "'CUT_D1'", 'Interior.SetVisible(5)', "Cutscene.Load('DATE1AP')" ],
[ "'CUT_D2'", 'Interior.SetVisible(5)', "Cutscene.Load('DATE1BP')" ],
[ "'CUT_D3'", 'Interior.SetVisible(0)', "Cutscene.Load('DATE1AB')" ],
[ "'CUT_D4'", 'Interior.SetVisible(0)', "Cutscene.Load('DATE1BB')" ],
[ "'CUT_D5'", 'Interior.SetVisible(9)', "Cutscene.Load('DATE2A')" ],
[ "'CUT_D6'", 'Interior.SetVisible(9)', "Cutscene.Load('DATE2B')" ],
[ "'CUT_D7'", 'Interior.SetVisible(4)', "Cutscene.Load('DATE3A')" ],
[ "'CUT_D8'", 'Interior.SetVisible(4)', "Cutscene.Load('DATE3B')" ],
[ "'CUT_D9'", 'Interior.SetVisible(5)', "Cutscene.Load('DATE4A')" ],
[ "'CUT_D10'", 'Interior.SetVisible(5)', "Cutscene.Load('DATE4B')" ],
[ "'CUT_D11'", 'Interior.SetVisible(6)', "Cutscene.Load('DATE5AB')" ],
[ "'CUT_D12'", 'Interior.SetVisible(6)', "Cutscene.Load('DATE5BB')" ],
[ "'CUT_D13'", 'Interior.SetVisible(1)', "Cutscene.Load('DATE5AT')" ],
[ "'CUT_D14'", 'Interior.SetVisible(1)', "Cutscene.Load('DATE5BT')" ],
[ "'CUT_D15'", 'Interior.SetVisible(7)', "Cutscene.Load('DATE6A1')" ],
[ "'CUT_D16'", 'Interior.SetVisible(7)', "Cutscene.Load('DATE6B1')" ],
[ "'CUT_D17'", 'Interior.SetVisible(1)', "Cutscene.Load('DATE6A2')" ],
[ "'CUT_D18'", 'Interior.SetVisible(1)', "Cutscene.Load('DATE6B2')" ],
[ "'CUT133'", 'Interior.SetVisible(5)', "Cutscene.Load('RIOT_1B')" ],
[ "'CUT141'", 'Interior.SetVisible(0)', "Cutscene.Load('Riot4e2')" ],
[ "'CUT107'", 'Interior.SetVisible(1)', "Cutscene.Load('CAS6b_2')" ],
[ "'CUT110'", 'Interior.SetVisible(2)', "Cutscene.Load('Cas_9a2')" ],
[ "'CUT120'", 'Interior.SetVisible(0)', "Cutscene.Load('CRASV2B')" ],
[ "'CUTTEST'", 'Interior.SetVisible(0)', "Cutscene.Load('CUTTEST')" ],
[ "'SC_02'", 'Interior.SetVisible(0)', "Cutscene.Load('SC_02')" ],
[ "'SC_03'", 'Interior.SetVisible(0)', "Cutscene.Load('SC_03')" ],
[ "'SC_04'", 'Interior.SetVisible(2)', "Cutscene.Load('SC_04')" ],
[ "'SC_05'", 'Interior.SetVisible(0)', "Cutscene.Load('SC_05')" ],
[ "'SC_06'", 'Interior.SetVisible(0)', "Cutscene.Load('SC_06')" ],
[ "'SC_07'", 'Interior.SetVisible(0)', "Cutscene.Load('SC_07')" ],
[ "'SC_08'", 'Interior.SetVisible(0)', "Cutscene.Load('SC_08')" ],
[ "'SC_09'", 'Interior.SetVisible(0)', "Cutscene.Load('SC_09')" ],
[ "'SC_10'", 'Interior.SetVisible(0)', "Cutscene.Load('SC_10')" ],
[ "'SC_11'", 'Interior.SetVisible(0)', "Cutscene.Load('SC_11')" ],
[ "'SC_12'", 'Interior.SetVisible(0)', "Cutscene.Load('SC_12')" ],
[ "'SC_13'", 'Interior.SetVisible(0)', "Cutscene.Load('SC_13')" ],
[ "'SC_13V'", 'Interior.SetVisible(0)', "Cutscene.Load('SC_13V')" ],
[ "'SC_14'", 'Interior.SetVisible(5)', "Cutscene.Load('SC_14')" ],
[ "'SC_15'", 'Interior.SetVisible(0)', "Cutscene.Load('SC_15')" ],
[ "'SC_16'", 'Interior.SetVisible(0)', "Cutscene.Load('SC_16')" ],
[ "'SC_18'", 'Interior.SetVisible(0)', "Cutscene.Load('SC_18')" ],
[ "'SC_19'", 'Interior.SetVisible(0)', "Cutscene.Load('SC_19')" ],
[ "'SC_20'", 'Interior.SetVisible(2)', "Cutscene.Load('SC_20')" ],
[ "'SC_21'", 'Interior.SetVisible(0)', "Cutscene.Load('SC_21')" ],
[ "'SC_21B'", 'Interior.SetVisible(0)', "Cutscene.Load('SC_21B')" ],
[ "'SC_22'", 'Interior.SetVisible(0)', "Cutscene.Load('SC_22')" ],
[ "'SC_23'", 'Interior.SetVisible(0)', "Cutscene.Load('SC_23')" ]
]

let h = []

let code = ''

x.forEach((a, b) => {
	h = h.concat(a[0])
})

x.forEach((a,b,c) => {
	code += `
if _Selected == ${b%12}
then
	${a[1]}
	${a[2]}
end
`
})

log(code)
//log(h)